title: George Lennard-Jones
show_downloads: True
theme: jekyll-theme-minimal

nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/
