theme: jekyll-theme-minimal
title: Name
logo: /assets/profile.png
description: test
show_downloads: false
google_analytics: # your ID
baseurl: "/data-diaries/"

markdown: kramdown
plugins:
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
    values:
      css: "assets/main.css"
